import axios from 'axios';
import Head from 'next/head'
import Image from 'next/image'
import {useState} from 'react';
import styles from '../styles/Home.module.scss'
import {auth} from '../firebase';
import { onAuthStateChanged } from '@firebase/auth';

export default function Home() {


  const [user, setUser] = useState('')
  const [file, setFile] = useState(null)


  //onAuthStateChanged(auth, (user) => setUser(user));                                    // This hangs the application whenever I use 'setState'.

  const handleGetUserData = async () => {
    let token;
    const user = auth.currentUser;

    
    if (user) {
      console.log(user)
      const url = 'http://localhost:8000/api/v1/users/';

      token = await auth.currentUser.getIdToken(true);

      try {

        const response = await axios.get(url, {
          headers: {
            Authorization: token
          }
        })

        console.log(response.data)
      } catch (error) {
        console.log(error)
      }
    } else {

      console.log('You are not authorized')
    }
  }


  const onFileChange = async (event) => {
    let token = await auth.currentUser.getIdToken(true)
    const response = await axios.get('http://localhost:8000/api/v1/file/get-url', {
                    headers: {
                      Authorization: token
                    }
                  })
          
    console.log(response.data.preSignedUrl)

    const upload = await axios.put(response.data.preSignedUrl, event.target.files[0], {

      headers: {
        'Content-Type': 'video/mp4'
      }
    })

    console.log(upload)
    
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className='checkauth__button'>
          <button onClick={handleGetUserData}>Get User Data</button>
          <h3>Above button sends token to backend, verifies the token, gets the authorized user data from mongodb and returns it.</h3>
        </div>

        <div className="upload__button">
          <input type="file" accept="video/mp4,video/x-m4v,video/*" onChange={(e) => onFileChange(e)} />
          <h1>Above button will open the explorer allowing us to choose a video file. Once the file is choosen, a handler function is triggered, which first sends the request to backend to verify the user credentials
            and then it uplaods the file to S3 bucket</h1>
        </div>
      </main>
    </div>
  )
}
